import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ClientProvider from "../components/ClientOnly";

const myFont = localFont({
  src: [
    {
      path: "../../public/fonts/dana-medium.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-myfont",
  display: "swap",
});

export const metadata: Metadata = {
  title: "My Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="fa"
      dir="rtl"
      suppressHydrationWarning
      className={myFont.variable}
    >
      <body className={` ${myFont.variable} antialiased`}>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
